journey0/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from journey.settings import MEDIA_ROOT
from app import views_product as productViews
from app import views_hotel as hotelViews
from app import views_login as loginViews
from app import views_note as noteViews
from app import views_center as centerViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', productViews.index),
    path('index/', productViews.index),
    path('product/', productViews.product),
    path('product/list/<int:cat>/', productViews.list),
    path('product/search/', productViews.search),
    path('product/detail/<int:id>/', productViews.detail),
    path('product/saveComment/', productViews.saveComment),
    path('product/commentList/<int:id>/', productViews.commentList),
    path('hotel/', hotelViews.index),
    path('hotel/search/', hotelViews.search),
    path('hotel/detail/<int:id>/', hotelViews.detail),
    path('hotel/saveOrder/', hotelViews.saveOrder),
    path('note/', noteViews.index),
    path('note/search/', noteViews.search),
    path('note/detail/<int:id>/', noteViews.detail),
    path('login/', loginViews.login),
    path('register/', loginViews.register),
    path('logout/', loginViews.logout),
    path('center/', centerViews.index),
    path('center/index/', centerViews.index),
    path('center/profile/', centerViews.profile),
    path('center/editPass/', centerViews.editPass),
    path('center/evaluated/', centerViews.evaluated),
    path('center/orderList/', centerViews.orderList),
    path('center/delOrder/<int:id>/', centerViews.delOrder),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':MEDIA_ROOT}),
]

app/models.py
from django.db import models

# 旅游咨询
class Note(models.Model):
    title = models.CharField(max_length=256,verbose_name='标题')
    content = models.TextField(verbose_name='内容')
    crt_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['crt_time']
        verbose_name = '旅游咨询'
        verbose_name_plural = '旅游咨询'

# 会员
class User(models.Model):
    GENDER_CHOICES = (
        ('male','男'),
        ('female','女'),
    )

    name = models.CharField(max_length=128,unique=True,verbose_name='登录名')
    password = models.CharField(max_length=256,verbose_name='密码')
    email = models.EmailField(unique=True,verbose_name='邮件')
    sex = models.CharField(max_length=32,choices=GENDER_CHOICES,default='男',verbose_name='性别')
    last_time = models.DateTimeField(verbose_name='最后登录时间')
    crt_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['crt_time']
        verbose_name = '会员'
        verbose_name_plural = '会员'

# 景点分类
class Category(models.Model):
    name=models.CharField(u'分类名',max_length=64)
    desc=models.TextField(u'描述')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "旅游景点分类"
        verbose_name_plural = "旅游景点分类"

# 旅游景点
class Product(models.Model):
    name=models.CharField(verbose_name='景点名',max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,verbose_name='分类')
    headImg = models.ImageField(verbose_name='图片',upload_to="%Y/%m/%d/", max_length=255)
    address=models.CharField(verbose_name='地址',max_length=500)
    price=models.IntegerField(verbose_name='价格')
    content = models.TextField(verbose_name='内容')
    openTime=models.CharField(verbose_name='开放时间',max_length=100)
    def __str__(self):
        return "{}，{}".format(self.name,self.category)
    class Meta:
        verbose_name = "旅游景点"
        verbose_name_plural = "旅游景点"

# 评价
class Comment(models.Model):
    POINT_CHOICES = (
         (1, u'一星好评'),
         (2, u'二星好评'),
         (3, u'三星好评'),
         (4, u'四星好评'),
         (5, u'五星好评'),
    )

    product = models.ForeignKey(Product, on_delete=models.CASCADE,verbose_name='旅游景点')
    user=models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='会员')
    point=models.IntegerField(choices=POINT_CHOICES,verbose_name='评分')
    content = models.TextField(verbose_name='内容')
    crt_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')

    def __str__(self):
        return "{}，{}，{}".format(self.product,self.user,self.get_point_display())
    class Meta:
        ordering = ['-crt_time']
        verbose_name = "旅游景点评价"
        verbose_name_plural = "旅游景点评价"

# 网站设置
class Config(models.Model):
    site=models.CharField(verbose_name='网站名',max_length=64)
    desc=models.TextField(verbose_name='简介')

    def __str__(self):
        return "网站名{}，字数：{}，简介：{}".format(self.site,len(self.desc),self.desc[:18])
    class Meta:
        verbose_name = "网站设置"
        verbose_name_plural = "网站设置"

# 酒店
class Hotel(models.Model):
    name=models.CharField(verbose_name='酒店名称',max_length=100)
    city=models.CharField(verbose_name='所在城市',max_length=64)
    address=models.CharField(verbose_name='酒店地址',max_length=200)
    desc = models.TextField(verbose_name='简介')
    def __str__(self):
        return "{}，{}，{}".format(self.name,self.city,self.address[:30])
    class Meta:
        verbose_name = "酒店"
        verbose_name_plural = "酒店"

# 酒店房间
class Room(models.Model):
    ROOM_TYPE_CHOICES = (
         (1, u'单人间'),
         (2, u'双人间'),
         (3, u'三人间'),
    )
    BREAKFAST_CHOICES = (
         (0, u'不含早餐'),
         (1, u'含早餐'),
    )
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE,verbose_name='酒店')
    roomType=models.IntegerField(choices=ROOM_TYPE_CHOICES,null=True,verbose_name='类型')
    breakfast=models.IntegerField(choices=BREAKFAST_CHOICES,null=True,verbose_name='是否含早')
    price=models.IntegerField(verbose_name='价格')
    desc = models.TextField(verbose_name='简介')
    num=models.IntegerField(verbose_name='数量')

    def __str__(self):
        return "{}，{}，{}，{}".format(self.get_roomType_display(),self.get_breakfast_display(),self.price,self.desc[:18])
    class Meta:
        verbose_name = "酒店房间"
        verbose_name_plural = "酒店房间"

# 酒店预定
class Order(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE,verbose_name='酒店')
    room = models.ForeignKey(Room, on_delete=models.CASCADE,verbose_name='房间')
    order_date=models.CharField(verbose_name='预约日期',max_length=64)
    user=models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='会员')
    num=models.IntegerField(verbose_name='数量')
    crt_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')

    def __str__(self):
        return "{}，{}，{}，数量:{}".format(self.hotel,self.room,self.user,self.num)
    class Meta:
        verbose_name = "酒店预定"
        verbose_name_plural = "酒店预定"

app/views.py
from django.shortcuts import render

# Create your views here.

app/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{config.site}}</title>
	<link href="/static/css/style.css" rel="stylesheet">
	<script src="/static/js/jquery.min.js"></script>
<style type="text/css">

</style>
</head>
<body>

	<div id="top">
		<div id="top_links">
			{% if request.session.is_login %}
			  <a href="/center/">当前在线：{{ request.session.user_name }}</a>
			  &nbsp;&nbsp;
			  <a href="/logout/">退出</a>
		   {% else %}
			  <a href="/login/">登录</a>
			  &nbsp;&nbsp;
			  <a href="/register/">注册</a>
		   {% endif %}
		</div>
	</div>
	<div id="head" style="">
		<div style="width:1020px;margin: 0 auto;text-align:left;height:80px;">
			<div style="float:left;width:680px;padding-top:15px;">
				<a href="/"><p style="color:#000000;font-size:28px;">{{config.site}}</p></a>
				<p style="color:#000000;font-size:16px;padding-top:15px;">{{config.desc}}</p>
			</div>
			<div style="float:right;width:300px;padding-top:20px;">
				<img src="/static/img/tu1.png" width="300"/>
			</div>
		</div>
	</div>

	<div id="main">

		<div id="main_left">
				{% block content %}{% endblock %}
		</div>
		<div id="main_right">
			{% if cats %}
			<h3>分类</h3>
			{% for cat in cats %}
			<p style="padding-left:20px;">
				<a href="/product/list/{{cat.id}}">{{cat.name}}</a>
			</p>
			{% endfor %}
			{% endif %}
			
			<p></p>
			<h3>链接</h3>
			<p style="padding-left:20px;"><a href="/product">旅游景点</a></p>
			<p style="padding-left:20px;"><a href="/hotel">酒店信息</a></p>
			<p style="padding-left:20px;"><a href="/note">旅游咨询</a></p>
			<p style="padding-left:20px;"><a href="/admin/">登录后台</a></p>
				
			{% if recProducts %}
			<h3>推荐</h3>
			{% for dict in recProducts %}
				<p style="padding-left:20px;"><a href="/product/detail/{{dict.id}}" title="{{dict.name}}">{{dict.name|slice:":10" }}</a></a></p>
			{% endfor %}
			{% endif %}

		</div>
		<div style="clear:both"></div>
	</div>
	<div id="foot">
		<p style="color:#ffffff;padding-top:20px;">python web作业-用Django做的旅游景点网站&nbsp;&nbsp;2021年1月12日</p>
	</div>

</body>
</html>

app/templates/center/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{config.site}}</title>
	<link href="/static/css/style.css" rel="stylesheet">
	<script src="/static/js/jquery.min.js"></script>
<style type="text/css">

</style>
</head>
<body>

	<div id="top">
		<div id="top_links">
			{% if request.session.is_login %}
			  <a href="/center/">当前在线：{{ request.session.user_name }}</a>
			  &nbsp;&nbsp;
			  <a href="/logout/">退出</a>
		   {% else %}
			  <a href="/login/">登录</a>
			  &nbsp;&nbsp;
			  <a href="/register/">注册</a>
		   {% endif %}
		</div>
	</div>
	<div id="head" style="">
		<div style="width:1020px;margin: 0 auto;text-align:left;height:80px;">
			<div style="float:left;width:680px;padding-top:15px;">
				<a href="/"><p style="color:#000000;font-size:28px;">{{config.site}}</p></a>
				<p style="color:#000000;font-size:16px;padding-top:15px;">{{config.desc}}</p>
			</div>
			<div style="float:right;width:300px;padding-top:20px;">
				<img src="/static/img/tu1.png" width="300"/>
			</div>
		</div>
	</div>

	<div id="main">

		<div id="center_left">
			<h3>菜单</h3>
			<ul class="menu">
				<li><a href="/center/index">会员中心</a></li>
				<li><a href="/center/profile">个人信息</a></li>
				<li><a href="/center/evaluated">评价过的景点</a></li>
				<li><a href="/center/orderList">宾馆预约一览</a></li>
			</ul>
		</div>
		<div id="center_right">
			{% block content %}{% endblock %}
		</div>
		<div style="clear:both"></div>
	</div>
	<div id="foot">
		<p style="color:#ffffff;padding-top:20px;">python web作业-用Django做的旅游景点网站&nbsp;&nbsp;2021年1月12日</p>
	</div>

</body>
</html>

app/templates/center/editPass.html
{% extends 'center/base.html' %}
{% load staticfiles %}

{% block content %}
<h3>密码修改</h3>
<br/>
<table cellspacing="3">
    <form action="/center/editPass/" id="form1" method="post" >
	{% csrf_token %}
  	<tr style="height:40px;">
		<td>密码：</td>
		<td><input type="password" id="password1" placeholder="密码" name="password1" style="padding:6px;"></td>
	</tr>
	
  	<tr style="height:40px;">
		<td>确认密码：</td>
		<td><input type="password" id="password2" placeholder="密码" name="password2" style="padding:6px;"></td>
	</tr>
	
	<tr style="text-align:center;height:50px;">
		<td colspan="2"><input type="button" value="保存" onclick="save()" style="padding:6px;width:100px"/> </td>
	</tr>
	</form>
</table>

<script type="text/javascript">

 function save(){
	
	 var password1 = $("#password1").val();
	 var password2 = $("#password2").val();
	
	 if(password1 == '' || password2 == '' ){
		alert("请输入密码");
		return false;
	 }
	 
	 if( password1.length < 6  ||  password2.length < 6 ){
		alert("密码必须超过6位");
		return false;
	 }
	 
	 if(password1 != password2 ){
		alert("确认密码与密码不符合");
		return false;
	 }
	 
	 $("#form1").submit();
 }

</script>
		
{% endblock %}

app/templates/center/evaluated.html
{% extends 'center/base.html' %}
{% load staticfiles %}

{% block content %}
<h3>评价过的景点</h3>
<br/>
<table class="gridtable" style="width:100%">
	<tr>
		<th>分类</th>
		<th>景点名称</th>
		<th>评价</th>
		<th>创建时间</th>
	</tr>
	{% for comm in comms %}
	<tr>
		<td align="center">{{comm.product.category.name}}</td>
		<td align="center">{{comm.product.name}}</td>
		<td align="center">{{comm.get_point_display}}</td>
		<td align="center">{{comm.crt_time}}</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

app/templates/center/index.html
{% extends 'center/base.html' %}
{% load staticfiles %}

{% block content %}
<h3>会员中心</h3>
<br/>

<p>欢迎{{user.name}}登录会员中心</p>

<p>最近登录时间：{{user.last_time}}，如果不是本人登录，请<a class="link" href="/center/editPass/">[修改]</a>密码</p>

{% endblock %}

app/templates/center/orderList.html
{% extends 'center/base.html' %}
{% load staticfiles %}

{% block content %}
<h3>宾馆预约一览</h3>
<br/>
<table class="gridtable" style="width:100%">
	<tr>
		<th>宾馆</th>
		<th>房间类型</th>
		<th>价格</th>
		<th>预定数量</th>
		<th>创建时间</th>
		<th>操作</th>
	</tr>
	{% for order in orders %}
	<tr>
		<td align="center">{{order.hotel.name}}</td>
		<td align="center">{{order.room.get_roomType_display}}</td>
		<td align="center">{{order.room.price}}</td>
		<td align="center">{{order.num}}</td>
		<td align="center">{{order.crt_time}}</td>
		<td align="center">
			<a href="/hotel/detail/{{order.hotel_id}}/" target="_blank" >[查看宾馆]</a>&nbsp;&nbsp;
			<a href="javascript:void(0)" onclick="delOrder({{order.id}})">[删除]</a>
		</td>
	</tr>
	{% endfor %}
</table>
	<script>
	// 删除
    function delOrder(id) {
        $.get("/center/delOrder/"+ id +"/", { },
       	 function (jd) {
            if (jd.result == 'success' ) {
            	alert("删除成功！");
				window.location.reload();
            } else {
				alert("删除失败！");
            }
        }, 'json');
    }
	</script>
{% endblock %}

app/templates/center/profile.html
{% extends 'center/base.html' %}
{% load staticfiles %}

{% block content %}
<h3>个人信息</h3>
<br/>
<table cellspacing="3">
	<tr style="height:40px;">
		<td width="100">用户名：</td>
		<td>{{user.name}}</td>
	</tr>
  
  	<tr style="height:40px;">
		<td>密码：</td>
		<td>******&nbsp;&nbsp;<a class="link" href="/center/editPass/">[修改]</a></td>
	</tr>
	
	<tr style="height:40px;">
		<td>邮件：</td>
		<td>{{user.email}}</td>
	</tr>

	<tr style="height:40px;">
		<td>性别：</td>
		<td>{{user.get_sex_display}}</td>
	</tr>
	
	<tr style="height:40px;">
		<td>创建时间：</td>
		<td>{{user.crt_time}}</td>
	</tr>
	
</table>
		
{% endblock %}

app/templates/commentList.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
			<div style="padding:10px;border-bottom: 1px solid #cccccc;">
				<h3>评价一览（{{comment_count}}）</h3>
			</div>
			{% for comment in comments %}
			<div style="padding:10px;border-bottom: 1px solid #cccccc;">
				<table width="100%">
					<tr>
						<td rowspan="2" width="15%" align="center">
						<img src="/static/img/user.png" width="50" height="50" /><br/>
						{{comment.user.name}}
						</td>
						<td width="60%">评价：{{comment.get_point_display}}</td>
						<td width="25%">{{comment.crt_time}}</td>
					</tr>
					<tr>
						<td colspan="2" style="padding:5px;">{{comment.content}}</td>
					</tr>
				</table>
			</div>
			{% endfor %}
			<div class="pagination"  style="padding:20px;text-align:center;">
			<span class="step-links">
				{% if comments.has_previous %}
					<a href="?page={{ comments.previous_page_number }}">上页</a>
				{% endif %}

				<span class="current">
					&nbsp;&nbsp;页码 {{ comments.number }} / {{ comments.paginator.num_pages }}&nbsp;&nbsp;
				</span>

				{% if comments.has_next %}
					<a href="?page={{ comments.next_page_number }}">下页</a>
				{% endif %}
			</span>
			</div>
{% endblock %}

app/templates/hotel.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
			<div style="padding:10px;border-bottom: 1px solid #cccccc;">
				<form  action="/hotel/search/" method="get">
						<p style="text-align:center;">
							酒店：<input type="type" name="key" placeholder="输入关键字" style="padding:6px;width:240px;" value="{{key}}"/>
							&nbsp;&nbsp;<input type="submit" value="检索"  style="padding:5px;width:60px;">
						</p>
				</form>
			</div>
			
			{% for hotel in hotels %}
			<div style="padding:10px;border-bottom: 1px solid #cccccc;">
				<table>
					<tr>
						<td rowspan="2" width="135"><img src="/static/img/tu2.png" width="120"/></td>
						<td ><a href="/hotel/detail/{{hotel.id}}"><h3>{{hotel.name}}</h3></a></td>
					</tr>
					<tr>
						<td>
							<p>城市：{{hotel.city}}&nbsp;&nbsp;&nbsp;&nbsp;地址：{{hotel.address}}</p>
							<p>{{hotel.desc|slice:":200" }}...</p>
						</td>
					</tr>
				</table>
			</div>
			{% endfor %}
			<div class="pagination"  style="padding:20px;text-align:center;">
			<span class="step-links">
				{% if hotels.has_previous %}
					<a href="?key={{key}}&page={{ hotels.previous_page_number }}">上页</a>
				{% endif %}

				<span class="current">
					&nbsp;&nbsp;页码 {{ hotels.number }} / {{ hotels.paginator.num_pages }}&nbsp;&nbsp;
				</span>

				{% if hotels.has_next %}
					<a href="?key={{key}}&page={{ hotels.next_page_number }}">下页</a>
				{% endif %}
			</span>
			</div>
{% endblock %}

app/templates/hotelDetail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
			<div style="padding:10px;">
				<h3>{{hotel.name}}</h3>
				<p>所在城市：{{hotel.city}}&nbsp;&nbsp;地址：{{hotel.address}}</p>
				<p>{{hotel.desc}}</p>
				<p>房间：</p>
				<table class="gridtable" style="width:100%">
				<tr>
					<th>类型</th>
					<th>是否含早</th>
					<th>价格</th>
					<th>简介</th>
					<th>数量</th>
				</tr>
				{% for room in rooms %}
				<tr>
					<td align="center">{{room.get_roomType_display}}</td>
					<td align="center">{{room.get_breakfast_display}}</td>
					<td align="center">{{room.price}}</td>
					<td>{{room.desc}}</td>
					<td>{{room.num}}</td>
				</tr>
				{% endfor %}
				</table>
				<br/>
				
				{% if request.session.is_login %}
				<h4>房间预定</h4>
				<form method="post" id="form1">
				{% csrf_token %}
					<p>房间类型：
						<select id="roomId" name="roomId" ><option value="">请选择</option>
							{% for room in rooms %}
							<option value="{{room.id}}">{{room.get_roomType_display}}</option>
							{% endfor %}
						</select>
					</p>
					<p>预定日期：
						<input id="orderDate" name="orderDate" type="text" value=""/>
					</p>
					<p>房间数量：
						<input id="orderNum" name="orderNum" type="text" value=""/>
					</p>
					<p>
						<input type="hidden" name="hotelId" value = "{{hotel.id}}" />
						<input type="hidden" name="userId" value = "{{ request.session.user_id }}" />
					</p>
					<p><input type="button" onclick="save()" value="提交" style="padding:5px;width:120px;"></p>
				</form>
				{% else %}
					<p>想预定的话，请先<a href="/login/">[登录]</a>。</p>
				{% endif %}
			</div>
<script>

	// 保存评论
	function save(){
		 var roomId=$("#roomId").val();
		 if(roomId ==null || roomId ==''){
			alert("请选择房间类型");
			return false;
		 }
	 
	 	 var orderDate=$("#orderDate").val();
		 if(orderDate ==null || orderDate ==''){
			alert("请输入日期");
			return false;
		 }
	 
		 var orderNum=$("#orderNum").val();
		 if(orderNum ==null || orderNum ==''){
			alert("请输入数量");
			return false;
		 }
		 
		$.post("/hotel/saveOrder/",
				$("#form1").serialize(),function(data){
				alert("提交成功");
				window.location.reload();
		});

	}
	
</script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
			<div style="padding:10px;border-bottom: 1px solid #cccccc;">
				<form  action="/product/search/" method="get">
						<p style="text-align:center;">
							旅游景点：<input type="type" name="key" placeholder="输入关键字" style="padding:6px;width:240px;" />
							&nbsp;&nbsp;<input type="submit" value="检索"  style="padding:5px;width:60px;">
						</p>
				</form>
			</div>
			
			<div style="clear:both"><br/></div>
			<h3>最新景点</h3>
			{% for product in products %}
			<div style="padding:10px;border-bottom: 1px solid #cccccc;width:220px;height:300px;float:left;">
				<a href="/product/detail/{{product.id}}"><img src="/media/{{product.headImg}}" width="200" height="150"/></a>
				<a href="/product/detail/{{product.id}}"><h4>{{product.name|slice:":16" }}</h4></a>
				<p>分类：{{product.category.name}}&nbsp;&nbsp;</p>
				<p>门票：<span style="color:#FF5E5A">{{product.price}}</span>元/人&nbsp;&nbsp;</p>
				<p>开放时间：{{product.openTime}}</p>
			</div>
			{% endfor %}
			
			<div style="clear:both"><br/></div>
			<h3>旅游咨询</h3>
			{% for note in notes %}
			<div style="padding:10px;border-bottom: 1px solid #cccccc;">
				<a href="/note/detail/{{note.id}}"><h4>{{note.title}}</h4></a>
				<p>{{note.content|slice:":100" }}...</p>
			</div>
			{% endfor %}

{% endblock %}

app/templates/login/index.html
{#login/templates/login/index.html#}
 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
	<link href="/static/css/style.css" rel="stylesheet">
	<style>

	</style>
</head>
<body>
     <div style="margin: 10% 30%;padding:30px;">
        <p style="border-bottom: 1px solid #c00;font-size:32px;font-weight:bolder">欢迎登录</p>
		<br/>
		{% if message %}
			<p style="color:red">{{ message }}</p>
        {% endif %}
		<br/><br/>
	    <p style="text-align:center;">- <a href="/">返回景点</a> &nbsp;|&nbsp; <a href="/login/">登录</a> -</p>
    </div>

</body>
</html>

app/templates/login/login.html
{#login/templates/login/login.html#}
 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
	<link href="/static/css/style.css" rel="stylesheet">
</head>
<body>
     <div style="margin: 5% 30%;padding:30px;border: 1px solid #bcbcbc;">
        <p style="border-bottom: 1px solid #020F69;font-size:32px;font-weight:bolder">欢迎登录</p>
		<br/>
		{% if message %}
			<div style="color:red">{{ message }}</div>
        {% endif %}
       <form action="/login/" method="post">
	   {% csrf_token %}
	   <table cellspacing="3">
            <tr style="height:40px;">
                <td style="width:120px;">用户名：</td>
                <td><input type="text" id="id_username" name="username" placeholder="用户名" autofocus required style="padding:6px;width:200px;"/></td>
            </tr>
          
            <tr style="height:40px;">
                <td style="width:120px;">密码：</td>
                <td><input type="password" id="id_password" placeholder="密码" name="password" required style="padding:6px;width:200px;"></td>
            </tr>

            <tr style="text-align:center;height:50px;">
				<td colspan="2"><input type="submit" value="登录" style="padding:6px;width:100px"/> </td>
			</tr>
		</table>
		<br/>
		<p style="text-align:center;">- <a href="/">返回景点</a> &nbsp;|&nbsp; <a href="/register">新用户注册</a> -</p>
		<br/>
        </form>
    </div>
 
 
 
</body>
</html>

app/templates/note.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
			<div style="padding:10px;border-bottom: 1px solid #cccccc;">
				<form  action="/note/search/" method="get">
						<p style="text-align:center;">
							<input type="type" name="key" placeholder="输入关键字" style="padding:6px;width:240px;" value="{{key}}"/>
							&nbsp;&nbsp;<input type="submit" value="检索"  style="padding:5px;width:60px;">
						</p>
				</form>
			</div>
			
			{% for note in notes %}
			<div style="padding:10px;border-bottom: 1px solid #cccccc;">
				<a href="/note/detail/{{note.id}}"><h4>{{note.title}}</h4></a>
				<p>{{note.content|slice:":100" }}......</p>
			</div>
			{% endfor %}
			<div class="pagination"  style="padding:20px;text-align:center;">
			<span class="step-links">
				{% if notes.has_previous %}
					<a href="?key={{key}}&page={{ notes.previous_page_number }}">上页</a>
				{% endif %}

				<span class="current">
					&nbsp;&nbsp;页码 {{ notes.number }} / {{ notes.paginator.num_pages }}&nbsp;&nbsp;
				</span>

				{% if notes.has_next %}
					<a href="?key={{key}}&page={{ notes.next_page_number }}">下页</a>
				{% endif %}
			</span>
			</div>
{% endblock %}

app/templates/noteDetail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
			<div style="padding:10px;">
				<h3>{{note.title}}</h3>
				<p>{{note.content}}</p>
			</div>
			
{% endblock %}